### ISSUE TITLE
Lent text is shown in Venite during Eastertide

### ISSUE THREAD

**Issue by davidbettis** [blocher/dailyoffice2019#107]
Repro:
* Go to https://www.dailyoffice2019.com/morning_prayer/2022-4-26/
* Examine Venite

Expected: no Lent suffix is present ("Today, if you will hear his voice..."), as season is Eastertide (2022-04-26) and not Lent

Actual: Lent suffix is present

<img width="1152" alt="Screen Shot 2022-04-26 at 2 22 07 PM" src="https://user-images.githubusercontent.com/459035/165394603-8762bcb3-2f25-4ae1-b657-10c89ad57290.png">

**Comment by blocher** [comment]
@davidbettis  I believe this is correct, following the 2019 prayerbook rubrics.  On the site, the rubric "The following verses may be omitted" is shown when it is not Lent (including Eastertide) but the rubric is hidden during Lent (when the remainder is required).

From the prayerbook:
<img width="527" alt="Screen Shot 2022-04-26 at 5 25 25 PM" src="https://user-images.githubusercontent.com/5084741/165395324-ff656179-5b2d-4514-a659-eec7576097c1.png">

**Comment by davidbettis** [comment]
Yeah, I agree. Closing this out.
