### ISSUE TITLE
Add a readings only view

### ISSUE THREAD

**Issue by blocher** [blocher/dailyoffice2019#26]
Megan Alicia Sateia meg.sateia@gmail.com

```I was wondering if it would be possible to have a tab with all of the Daily Office Bible readings for the day all in one place with just the readings (no liturgy)? Or maybe you already have this feature and I just haven’t seen it?```

```For my own readings, I would like them to be on the same page. With the psalms. 60 day psalter. And if it’s possible to toggle between abbreviated and full readings, that sounds cool, but otherwise the full readings.```

**Comment by perryholden** [comment]
@blocher - It seems like this was added by commit `2fcf4d19` in 2022. Can this be closed?
